import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Auto Attack",
    Modifier: "1st Auto",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Auto",
    "Skill Ratio": 1.3,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Auto",
    "Skill Ratio": 0.6,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Auto [2nd Hit]",
    "Skill Ratio": 1.1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Auto",
    "Skill Ratio": 0.9,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Auto [2nd Hit]",
    "Skill Ratio": 1.4,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Power Strike",
    Modifier: "1st Finisher",
    "Skill Ratio": 1.4,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "1st Finisher [2nd Hit]",
    "Skill Ratio": 1.8,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "2nd Finisher",
    "Skill Ratio": 1.9,
    "DMG Cap": 29999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Finisher [2nd Hit]",
    "Skill Ratio": 1.2,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "2nd Finisher [3rd Hit]",
    "Skill Ratio": 0.3,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "3rd Finisher [1st-3rd]",
    "Skill Ratio": 1.3,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "3rd Finisher [4th Hit]",
    "Skill Ratio": 1,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "4th Finisher",
    "Skill Ratio": 1,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "4th Finisher [2nd Hit]",
    "Skill Ratio": 0.8,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "4th Finisher [3rd Hit]",
    "Skill Ratio": 1.8,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Power Raise",
    Modifier: "No Charge",
    "Skill Ratio": 1.7,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "No Charge [2nd Hit]",
    "Skill Ratio": 1.1,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "1 Charge [1st & 2nd]",
    "Skill Ratio": 1.1,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "1 Charge [3rd Hit]",
    "Skill Ratio": 2.6,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "Full Charge [1st-4th]",
    "Skill Ratio": 1.3,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "Full Charge [5th Hit]",
    "Skill Ratio": 3.65,
    "DMG Cap": 29999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "Link Attack",
    Modifier: "",
    "Skill Ratio": 6,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Li",
  },
  {
    Skill: "SBA",
    Modifier: "Activation Hit",
    "Skill Ratio": 0.96,
    "DMG Cap": 64999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "1st Hit",
    "Skill Ratio": 1.44,
    "DMG Cap": 64999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 2.64,
    "DMG Cap": 64999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 4.08,
    "DMG Cap": 64999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 6.24,
    "DMG Cap": 64999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "Rain of Arrows",
    Modifier: "",
    "Skill Ratio": 0.83,
    "DMG Cap": 14999,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "Overdrive Surge",
    Modifier: "Arts I",
    "Skill Ratio": 4.04,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Arts II",
    "Skill Ratio": 5,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Arts III",
    "Skill Ratio": 6,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Arts IV",
    "Skill Ratio": 8.34,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Armor Break",
    Modifier: "",
    "Skill Ratio": 3.42,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Decimate",
    Modifier: "",
    "Skill Ratio": 1.42,
    "DMG Cap": 19999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Reginleiv",
    Modifier: "",
    "Skill Ratio": 1.58,
    "DMG Cap": 14999,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "Dispel",
    Modifier: "",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "RaSk",
  },
];

export const captainSkills = convertSkills(skillsJson);
