import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Melee",
    Modifier: "First",
    "Skill Ratio": 1.5,
    "DMG Cap": 14999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Second",
    "Skill Ratio": 1.71,
    "DMG Cap": 14999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Third",
    "Skill Ratio": 2.2,
    "DMG Cap": 14999,
    CD: 0,
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "Jump",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "Shoot",
    Modifier: "Stand",
    "Skill Ratio": 1.6,
    "DMG Cap": 14999,
    CD: 0,
    Classification: "NoRa",
  },
  {
    Skill: "",
    Modifier: "Jump",
    "Skill Ratio": 1.61,
    "DMG Cap": 14999,
    CD: 0,
    Classification: "NoRa",
  },
  {
    Skill: "",
    Modifier: "Sniper",
    "Skill Ratio": 2.62,
    "DMG Cap": 24999,
    CD: 0,
    Classification: "NoRa",
  },
  {
    Skill: "",
    Modifier: "Charged",
    "Skill Ratio": 2.99,
    "DMG Cap": 24999,
    CD: 0,
    Classification: "NoRaCh",
  },
  {
    Skill: "Grenade",
    Modifier: "Normal",
    "Skill Ratio": 2.6,
    "DMG Cap": 74999,
    CD: 0,
    Classification: "NoTh",
  },
  {
    Skill: "Grenade",
    Modifier: "Jump",
    "Skill Ratio": 2.59,
    "DMG Cap": 24999,
    CD: 0,
    Classification: "NoTh",
  },
  {
    Skill: "Grenade",
    Modifier: "Aimed",
    "Skill Ratio": 4.43,
    "DMG Cap": 74999,
    CD: 0,
    Classification: "NoTh",
  },
  {
    Skill: "Grenade",
    Modifier: "Sniper",
    "Skill Ratio": 7,
    "DMG Cap": 74999,
    CD: 0,
    Classification: "NoTh",
  },
  {
    Skill: "Link Attack",
    Modifier: "",
    "Skill Ratio": 5.99,
    "DMG Cap": 99999,
    CD: 0,
    Classification: "NoRaLi",
  },
  {
    Skill: "SBA",
    Modifier: "Opener",
    "Skill Ratio": 0.98,
    "DMG Cap": 99999,
    CD: 0,
    Classification: "SbRa",
  },
  {
    Skill: "",
    Modifier: "First",
    "Skill Ratio": 3.64,
    "DMG Cap": 129999,
    CD: 0,
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Second",
    "Skill Ratio": 5.45,
    "DMG Cap": 129999,
    CD: 0,
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Total",
    "Skill Ratio": 0,
    "DMG Cap": 259998,
    CD: 0,
    Classification: "",
  },
  {
    Skill: "Sumrak",
    Modifier: "Single",
    "Skill Ratio": 2.4,
    "DMG Cap": 14999,
    CD: 30,
    Classification: "SkRa",
  },
  {
    Skill: "Detonator",
    Modifier: "0%",
    "Skill Ratio": 4,
    "DMG Cap": 149999,
    CD: 45,
    Classification: "SkRa",
  },
  {
    Skill: "",
    Modifier: "50%",
    "Skill Ratio": 9.36,
    "DMG Cap": 149999,
    CD: 45,
    Classification: "SkRaCh",
  },
  {
    Skill: "",
    Modifier: "100% First",
    "Skill Ratio": 21.62,
    "DMG Cap": 149999,
    CD: 45,
    Classification: "SkRaCh",
  },
  {
    Skill: "",
    Modifier: "100% Second",
    "Skill Ratio": 10.3,
    "DMG Cap": 149999,
    CD: 45,
    Classification: "SkRaCh",
  },
  {
    Skill: "Intercept",
    Modifier: "",
    "Skill Ratio": 3.65,
    "DMG Cap": 69999,
    CD: 12,
    Classification: "SkRa",
  },
  {
    Skill: "Armor-Piercing Round",
    Modifier: "",
    "Skill Ratio": 4.95,
    "DMG Cap": 44999,
    CD: 60,
    Classification: "SkRa",
  },
  {
    Skill: "Venom Grenade",
    Modifier: "",
    "Skill Ratio": 1,
    "DMG Cap": 19999,
    CD: 80,
    Classification: "SkRa",
  },
  {
    Skill: "Paralyzing Bullet",
    Modifier: "",
    "Skill Ratio": 2.4,
    "DMG Cap": 19999,
    CD: 120,
    Classification: "SkRa",
  },
  {
    Skill: "Disruptor",
    Modifier: "",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: 55,
    Classification: "SkRa",
  },
];

export const eugenSkills = convertSkills(skillsJson);
