import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Auto Attack",
    Modifier: "1st Auto",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Auto",
    "Skill Ratio": 1.5,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Auto(Timed)",
    "Skill Ratio": 2.3,
    "DMG Cap": 29999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Auto",
    "Skill Ratio": 2.5,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Auto(Timed)",
    "Skill Ratio": 3.6,
    "DMG Cap": 29999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Auto",
    "Skill Ratio": 2.5,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Auto(Timed)",
    "Skill Ratio": 6,
    "DMG Cap": 29999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "5th Auto",
    "Skill Ratio": 3.4,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "5th Auto(Timed)",
    "Skill Ratio": 9.8,
    "DMG Cap": 29999,
    CD: 0,
    Classification: "NoFi",
  },
  {
    Skill: "Air Auto",
    Modifier: "1st Auto",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Auto",
    "Skill Ratio": 1.18,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Auto (Timed)",
    "Skill Ratio": 1.8,
    "DMG Cap": 29999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Auto",
    "Skill Ratio": 1.5,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "3rd Auto (Timed)",
    "Skill Ratio": 2.7,
    "DMG Cap": 29999,
    CD: 0,
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "Launch",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Plunge",
    "Skill Ratio": 1.71,
    "DMG Cap": 9999,
    CD: 0,
    Classification: "No",
  },
  {
    Skill: "Raging Fist",
    Modifier: "No Rage",
    "Skill Ratio": 1,
    "DMG Cap": 29999,
    CD: 0,
    Classification: "NoCh",
  },
  {
    Skill: "Raging Fist",
    Modifier: "3 Rage (Uncharged)",
    "Skill Ratio": 1.87,
    "DMG Cap": 59999,
    CD: 0,
    Classification: "NoCh",
  },
  {
    Skill: "Raging Fist",
    Modifier: "3 Rage",
    "Skill Ratio": 9.68,
    "DMG Cap": 59999,
    CD: 0,
    Classification: "NoCh",
  },
  {
    Skill: "Raging Fist",
    Modifier: "5 Rage (Uncharged)",
    "Skill Ratio": 2.43,
    "DMG Cap": 104999,
    CD: 0,
    Classification: "NoCh",
  },
  {
    Skill: "Raging Fist",
    Modifier: "5 Rage",
    "Skill Ratio": 15.74,
    "DMG Cap": 104999,
    CD: 0,
    Classification: "NoCh",
  },
  {
    Skill: "Raging Fist",
    Modifier: "7 Rage (Uncharged)",
    "Skill Ratio": 3.04,
    "DMG Cap": 179999,
    CD: 0,
    Classification: "NoCh",
  },
  {
    Skill: "Raging Fist",
    Modifier: "7 Rage",
    "Skill Ratio": 21.45,
    "DMG Cap": 179999,
    CD: 0,
    Classification: "NoCh",
  },
  {
    Skill: "Raging Fist",
    Modifier: "10 Rage (Uncharged)",
    "Skill Ratio": 3.96,
    "DMG Cap": 299999,
    CD: 0,
    Classification: "NoCh",
  },
  {
    Skill: "Raging Fist",
    Modifier: "10 Rage",
    "Skill Ratio": 29.93,
    "DMG Cap": 299999,
    CD: 0,
    Classification: "NoCh",
  },
  {
    Skill: "Skills",
    Modifier: "Iron Shoulder",
    "Skill Ratio": 5.5,
    "DMG Cap": 64999,
    CD: 15,
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Arhat Skybreaker (lowest hit)",
    "Skill Ratio": 3,
    "DMG Cap": 64999,
    CD: 25,
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Arhat Skybreaker",
    "Skill Ratio": 8.33,
    "DMG Cap": 64999,
    CD: 25,
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Infernal Stomp",
    "Skill Ratio": 2.5,
    "DMG Cap": 19999,
    CD: 120,
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Branding Palm(No Counter)",
    "Skill Ratio": 3,
    "DMG Cap": 24999,
    CD: 45,
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Branding Palm(Counter) - Lowest hit",
    "Skill Ratio": 1.25,
    "DMG Cap": 24999,
    CD: 45,
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Branding Palm(Counter)",
    "Skill Ratio": 4.83,
    "DMG Cap": 24999,
    CD: 45,
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Lion Stance",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    CD: 90,
    Classification: "",
  },
  {
    Skill: "",
    Modifier: "True Avidya",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    CD: 60,
    Classification: "",
  },
  {
    Skill: "",
    Modifier: "Dhyana",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    CD: 80,
    Classification: "",
  },
  {
    Skill: "",
    Modifier: "Eternal Rage",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    CD: 150,
    Classification: "",
  },
  {
    Skill: "Link Attack",
    Modifier: "",
    "Skill Ratio": 6,
    "DMG Cap": 99999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "SBA",
    Modifier: "Activation Hit",
    "Skill Ratio": 1,
    "DMG Cap": 99999,
    CD: 0,
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Multi Hit 1",
    "Skill Ratio": 2,
    "DMG Cap": 54999,
    CD: 0,
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Multi Hit 2/3/4",
    "Skill Ratio": 1,
    "DMG Cap": 54999,
    CD: 0,
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Multi Hit 5",
    "Skill Ratio": 5.5,
    "DMG Cap": 54999,
    CD: 0,
    Classification: "Sb",
  },
];

export const ghandagozaSkills = convertSkills(skillsJson);
