import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Auto Attack",
    Modifier: "1st Hit",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 2.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 2.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Lunge",
    Modifier: "1st Hit",
    "Skill Ratio": 1.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 7,
    "DMG Cap": 49999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Charged Lunge",
    Modifier: "1st Hit",
    "Skill Ratio": 0.7,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 0.7,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 0.7,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 1.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "5th Hit",
    "Skill Ratio": 7,
    "DMG Cap": 49999,
    CD: "",
    Classification: "NoChFi",
  },
  {
    Skill: "Launcher",
    Modifier: "",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Aerial Attack",
    Modifier: "1st Hit",
    "Skill Ratio": 1.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 2.1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1.6,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Aerial Barrage",
    Modifier: "",
    "Skill Ratio": 1.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Reginleiv Recidiv",
    Modifier: "Each Hit",
    "Skill Ratio": 2.5,
    "DMG Cap": 29999,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "Unbound",
    Modifier: "Melee Hit",
    "Skill Ratio": 3.33,
    "DMG Cap": 59999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Projectile",
    "Skill Ratio": 6.67,
    "DMG Cap": 59999,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "Ragnarok Form",
    Modifier: "",
    "Skill Ratio": 3.08,
    "DMG Cap": 19999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Scourge",
    Modifier: "",
    "Skill Ratio": 11.25,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Fourfold Vengeance",
    Modifier: "Uncharged",
    "Skill Ratio": 3.33,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSk",
  },
  {
    Skill: "",
    Modifier: "1 Charge",
    "Skill Ratio": 7.92,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSk",
  },
  {
    Skill: "",
    Modifier: "2 Charge",
    "Skill Ratio": 18.33,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSk",
  },
  {
    Skill: "",
    Modifier: "Max Charge",
    "Skill Ratio": 39.17,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSk",
  },
  {
    Skill: "Never Enough",
    Modifier: "1st Hit",
    "Skill Ratio": 1.58,
    "DMG Cap": 34999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.83,
    "DMG Cap": 34999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 3.13,
    "DMG Cap": 34999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 4.17,
    "DMG Cap": 34999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Dragonform Transformation",
    Modifier: "1st Hit",
    "Skill Ratio": 1.05,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 2.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "Dragonform Auto Attack",
    Modifier: "1st Hit",
    "Skill Ratio": 1.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.7,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit to 10th Hit",
    "Skill Ratio": 1.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "11th Hit",
    "Skill Ratio": 6.6,
    "DMG Cap": 49999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Dragonform Light Blast",
    Modifier: "1st Hit",
    "Skill Ratio": 0.8,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 0.8,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "",
    Modifier: "3rd Hit to 10th Hit",
    "Skill Ratio": 0.8,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "",
    Modifier: "11th to 18th Hit",
    "Skill Ratio": 0.7,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "",
    Modifier: "19th Hit",
    "Skill Ratio": 2.1,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoRaFi",
  },
  {
    Skill: "Dragonform Launcher",
    Modifier: "",
    "Skill Ratio": 1.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Dragonform Aerial Attack",
    Modifier: "1st Hit",
    "Skill Ratio": 1.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.7,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd and 4th Hit",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Dragonform Aerial Barrage",
    Modifier: "1st Hit",
    "Skill Ratio": 2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.4,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Dragonform Reginleiv Recidiv",
    Modifier: "1st Hit",
    "Skill Ratio": 3.33,
    "DMG Cap": 24999,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 3.33,
    "DMG Cap": 24999,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 5.25,
    "DMG Cap": 24999,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "Dragonform Scourge",
    Modifier: "Each Hit",
    "Skill Ratio": 16.67,
    "DMG Cap": 99999,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "Never Enough",
    Modifier: "Each Hit",
    "Skill Ratio": 6.42,
    "DMG Cap": 54999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Godmight Transformation",
    Modifier: "1st Hit",
    "Skill Ratio": 1.2,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 3,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoRaSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 2.2,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoRaSp",
  },
  {
    Skill: "Godmight Auto Attack",
    Modifier: "1st Hit",
    "Skill Ratio": 1.5,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.8,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 3.4,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 4.2,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Godmight Lunge",
    Modifier: "1st Hit",
    "Skill Ratio": 2.7,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 9.4,
    "DMG Cap": 49999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Godmight Charged Lunge",
    Modifier: "1st Hit",
    "Skill Ratio": 1,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoChSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoChSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoChSp",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 1.8,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoChSp",
  },
  {
    Skill: "",
    Modifier: "5th Hit",
    "Skill Ratio": 7,
    "DMG Cap": 49999,
    CD: "",
    Classification: "NoChFiSp",
  },
  {
    Skill: "Godmight Super Combo",
    Modifier: "1st Hit to 15th Hit",
    "Skill Ratio": 1.3,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "16th Hit",
    "Skill Ratio": 14,
    "DMG Cap": 49999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "17th Hit",
    "Skill Ratio": 10,
    "DMG Cap": 49999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Godmight Charged Super Combo",
    Modifier: "1st Hit to 15th Hit",
    "Skill Ratio": 1.7,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "16th Hit",
    "Skill Ratio": 14,
    "DMG Cap": 49999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "17th Hit",
    "Skill Ratio": 12.5,
    "DMG Cap": 49999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Godmight Launcher",
    Modifier: "",
    "Skill Ratio": 1.5,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "Godmight Aerial Attack",
    Modifier: "1st Hit",
    "Skill Ratio": 1.8,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 2.1,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 2.4,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "Godmight Aerial Barrage",
    Modifier: "",
    "Skill Ratio": 2.7,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Godmight Reginleiv Recidiv",
    Modifier: "Each Hit",
    "Skill Ratio": 3.67,
    "DMG Cap": 29999,
    CD: "",
    Classification: "RaSkSp",
  },
  {
    Skill: "Godmight Charged Reginleiv Recidiv",
    Modifier: "Each Hit",
    "Skill Ratio": 4.88,
    "DMG Cap": 29999,
    CD: "",
    Classification: "RaSkSp",
  },
  {
    Skill: "Godmight Unbound",
    Modifier: "Melee Hit",
    "Skill Ratio": 5.08,
    "DMG Cap": 59999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "Projectile",
    "Skill Ratio": 10.83,
    "DMG Cap": 59999,
    CD: "",
    Classification: "RaSkSp",
  },
  {
    Skill: "Godmight Charged Unbound",
    Modifier: "Melee Hit",
    "Skill Ratio": 6.67,
    "DMG Cap": 59999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "Projectile",
    "Skill Ratio": 12.92,
    "DMG Cap": 59999,
    CD: "",
    Classification: "RaSkSp",
  },
  {
    Skill: "Godmight Ragnarok Form",
    Modifier: "",
    "Skill Ratio": 2.83,
    "DMG Cap": 19999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Godmight Charged Ragnarok Form",
    Modifier: "",
    "Skill Ratio": 3.71,
    "DMG Cap": 19999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Godmight Scourge",
    Modifier: "",
    "Skill Ratio": 16.67,
    "DMG Cap": 99999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Godmight Charged Scourge",
    Modifier: "",
    "Skill Ratio": 21.67,
    "DMG Cap": 99999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Godmight Fourfold Vengeance",
    Modifier: "Uncharged",
    "Skill Ratio": 5,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSkSp",
  },
  {
    Skill: "",
    Modifier: "1 Charge",
    "Skill Ratio": 11.67,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSkSp",
  },
  {
    Skill: "",
    Modifier: "2 Charge",
    "Skill Ratio": 27.5,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSkSp",
  },
  {
    Skill: "",
    Modifier: "Max Charge",
    "Skill Ratio": 46.67,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSkSp",
  },
  {
    Skill: "Godmight Charged Fourfold Vengeance",
    Modifier: "Uncharged",
    "Skill Ratio": 6.67,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSkSp",
  },
  {
    Skill: "",
    Modifier: "1 Charge",
    "Skill Ratio": 15.42,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSkSp",
  },
  {
    Skill: "",
    Modifier: "2 Charge",
    "Skill Ratio": 35,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSkSp",
  },
  {
    Skill: "",
    Modifier: "Max Charge",
    "Skill Ratio": 46.67,
    "DMG Cap": 199999,
    CD: "",
    Classification: "ChSkSp",
  },
  {
    Skill: "Godmight Never Enough",
    Modifier: "1st Hit",
    "Skill Ratio": 2.5,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 2.75,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 4.75,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 6,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Godmight Charged Never Enough",
    Modifier: "1st Hit",
    "Skill Ratio": 3.17,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 3.67,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 6.17,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 7.83,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Link Attack",
    Modifier: "",
    "Skill Ratio": 6.1,
    "DMG Cap": 99999,
    CD: "",
    Classification: "NoLi",
  },
  {
    Skill: "Dragonform Link Attack",
    Modifier: "",
    "Skill Ratio": 6.1,
    "DMG Cap": 99999,
    CD: "",
    Classification: "NoLi",
  },
  {
    Skill: "Godmight Link Attack",
    Modifier: "",
    "Skill Ratio": 6.1,
    "DMG Cap": 99999,
    CD: "",
    Classification: "NoLi",
  },
  {
    Skill: "Godmight Charged Link Attack",
    Modifier: "",
    "Skill Ratio": 8.5,
    "DMG Cap": 99999,
    CD: "",
    Classification: "NoLiSp",
  },
  {
    Skill: "SBA",
    Modifier: "",
    "Skill Ratio": 10,
    "DMG Cap": 257840,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "Dragonform SBA",
    Modifier: "",
    "Skill Ratio": 11.83,
    "DMG Cap": 269999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "Godmight SBA",
    Modifier: "",
    "Skill Ratio": 16,
    "DMG Cap": 89999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "Godmight Charged SBA",
    Modifier: "",
    "Skill Ratio": 19.17,
    "DMG Cap": 89999,
    CD: "",
    Classification: "SbSp",
  },
];

export const idSkills = convertSkills(skillsJson);
