import { SkillConstant } from "@/types/skill.types";

export const ioSkills: SkillConstant[] = [
  {
    skill: "Auto Attack",
    modifier: "",
    skillRatio: 1,
    dmgCap: 9999,
    cd: 0,
    classification: {
      normal: true,
      ranged: true,
      charged: false,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Charge Attack",
    modifier: "",
    skillRatio: 4.3,
    dmgCap: 39999,
    cd: 0,
    classification: {
      normal: true,
      ranged: true,
      charged: true,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Link Attack",
    modifier: "First 6 hits",
    skillRatio: 3.6,
    dmgCap: 99996,
    cd: 0,
    classification: {
      normal: false,
      ranged: true,
      charged: false,
      skill: false,
      skyboundArt: false,
      linkAttack: true,
      finisher: false,
    },
  },
  {
    skill: "Link Attack",
    modifier: "Last hit",
    skillRatio: 1.8,
    dmgCap: 16666,
    cd: 0,
    classification: {
      normal: false,
      ranged: true,
      charged: false,
      skill: false,
      skyboundArt: false,
      linkAttack: true,
      finisher: false,
    },
  },
  {
    skill: "SBA",
    modifier: "Opener",
    skillRatio: 1,
    dmgCap: 99999,
    cd: 0,
    classification: {
      normal: false,
      ranged: true,
      charged: false,
      skill: false,
      skyboundArt: true,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "SBA",
    modifier: "Hit 1",
    skillRatio: 0.6,
    dmgCap: 34999,
    cd: 0,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: true,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "SBA",
    modifier: "Hit 2",
    skillRatio: 0.8,
    dmgCap: 34999,
    cd: 0,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: true,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "SBA",
    modifier: "Hit 3",
    skillRatio: 0.6,
    dmgCap: 34999,
    cd: 0,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: true,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "SBA",
    modifier: "Hit 4",
    skillRatio: 0.8,
    dmgCap: 34999,
    cd: 0,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: true,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "SBA",
    modifier: "Hit 5",
    skillRatio: 1,
    dmgCap: 34999,
    cd: 0,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: true,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "SBA",
    modifier: "Hit 6",
    skillRatio: 0.8,
    dmgCap: 34999,
    cd: 0,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: true,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "SBA",
    modifier: "Hit 7",
    skillRatio: 1,
    dmgCap: 34999,
    cd: 0,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: true,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "SBA",
    modifier: "Hit 8",
    skillRatio: 1,
    dmgCap: 34999,
    cd: 0,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: true,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Stargaze",
    modifier: "I",
    skillRatio: 2.3,
    dmgCap: 29999,
    cd: 0,
    classification: {
      normal: true,
      ranged: true,
      charged: true,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Stargaze",
    modifier: "II",
    skillRatio: 6.1,
    dmgCap: 59998,
    cd: 0,
    classification: {
      normal: true,
      ranged: true,
      charged: true,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Stargaze",
    modifier: "III",
    skillRatio: 10.6,
    dmgCap: 104996,
    cd: 0,
    classification: {
      normal: true,
      ranged: true,
      charged: true,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Stargaze",
    modifier: "IV",
    skillRatio: 16,
    dmgCap: 179994,
    cd: 0,
    classification: {
      normal: true,
      ranged: true,
      charged: true,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Stargaze",
    modifier: "V",
    skillRatio: 29.6,
    dmgCap: 299990,
    cd: 0,
    classification: {
      normal: true,
      ranged: true,
      charged: true,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Freeze",
    modifier: "Total",
    skillRatio: 7.7,
    dmgCap: 49995,
    cd: 20,
    classification: {
      normal: false,
      ranged: true,
      charged: false,
      skill: true,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Fire",
    modifier: "Melee",
    skillRatio: 1.32,
    dmgCap: 54999,
    cd: 20,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: true,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Fire",
    modifier: "Pass-Through",
    skillRatio: 3.3,
    dmgCap: 54999,
    cd: 20,
    classification: {
      normal: false,
      ranged: true,
      charged: false,
      skill: true,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Fire",
    modifier: "Explosion",
    skillRatio: 6.6,
    dmgCap: 54999,
    cd: 20,
    classification: {
      normal: false,
      ranged: true,
      charged: false,
      skill: true,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Flowery Seven",
    modifier: "Uncharged",
    skillRatio: 27.72,
    dmgCap: 489993,
    cd: 180,
    classification: {
      normal: false,
      ranged: true,
      charged: true,
      skill: true,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Flowery Seven",
    modifier: "Charged",
    skillRatio: 46.97,
    dmgCap: 979993,
    cd: 180,
    classification: {
      normal: false,
      ranged: true,
      charged: true,
      skill: true,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
      oc: true,
    },
  },
  {
    skill: "Lightning",
    modifier: "",
    skillRatio: 7,
    dmgCap: 69999,
    cd: 150,
    classification: {
      normal: false,
      ranged: true,
      charged: false,
      skill: true,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Gravity Well",
    modifier: "Total",
    skillRatio: 26.4,
    dmgCap: 319984,
    cd: 80,
    classification: {
      normal: false,
      ranged: true,
      charged: false,
      skill: true,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Concentration",
    modifier: "",
    skillRatio: 0,
    dmgCap: 0,
    cd: 80,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Healing Winds",
    modifier: "",
    skillRatio: 0,
    dmgCap: 0,
    cd: 50,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
  {
    skill: "Mystic Vortex",
    modifier: "",
    skillRatio: 0,
    dmgCap: 0,
    cd: 120,
    classification: {
      normal: false,
      ranged: false,
      charged: false,
      skill: false,
      skyboundArt: false,
      linkAttack: false,
      finisher: false,
    },
  },
];
