import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Auto",
    Modifier: "1st Hit",
    "Skill Ratio": 1.2,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.4,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1.5,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th - 11th Hit",
    "Skill Ratio": 0.45,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "12th Hit",
    "Skill Ratio": 2,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Auto (50% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.49,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.74,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1.86,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th - 11th Hit",
    "Skill Ratio": 0.56,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "12th Hit",
    "Skill Ratio": 2.48,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Auto (100% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.58,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.85,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1.98,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th - 11th Hit",
    "Skill Ratio": 0.59,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "12th Hit",
    "Skill Ratio": 2.65,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Launch",
    Modifier: "",
    "Skill Ratio": 1.2,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Launch (50% Gauge)",
    Modifier: "",
    "Skill Ratio": 1.49,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Launch (100% Gauge)",
    Modifier: "",
    "Skill Ratio": 1.58,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Aerial Barrage",
    Modifier: "",
    "Skill Ratio": 1.9,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Aerial Barrage (50% Gauge)",
    Modifier: "",
    "Skill Ratio": 2.36,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Aerial Barrage (100% Gauge)",
    Modifier: "",
    "Skill Ratio": 2.51,
    "DMG Cap": 9999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "Air Combo",
    Modifier: "1st Hit",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1.2,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Air Combo (50% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.24,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.24,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1.49,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Air Combo (100% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.32,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.32,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1.59,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "1st Auto Finisher",
    Modifier: "",
    "Skill Ratio": 1.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "2nd Auto Finisher",
    Modifier: "",
    "Skill Ratio": 1.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "3rd Auto Finisher",
    Modifier: "",
    "Skill Ratio": 3,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "1st Auto Finisher (50% Gauge)",
    Modifier: "",
    "Skill Ratio": 1.49,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "2nd Auto Finisher (50% Gauge)",
    Modifier: "",
    "Skill Ratio": 1.86,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "3rd Auto Finisher (50% Gauge)",
    Modifier: "",
    "Skill Ratio": 3.72,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "1st Auto Finisher (100% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.59,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit (Ares)",
    "Skill Ratio": 0.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "2nd Auto Finisher (100% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.98,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit (Ares)",
    "Skill Ratio": 1.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "3rd Auto Finisher (100% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 3.97,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit (Ares)",
    "Skill Ratio": 2.58,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Combo Finisher",
    Modifier: "1st Hit",
    "Skill Ratio": 1.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 2.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Combo Finisher (50% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.86,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.24,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 2.22,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Combo Finisher (100% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.98,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit (Ares)",
    "Skill Ratio": 1.3,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1.32,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "4th Hit (Ares)",
    "Skill Ratio": 2.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "5th",
    "Skill Ratio": 3.3,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Oathsworn Blade",
    Modifier: "1st Hit",
    "Skill Ratio": 1.3,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.4,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 0.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 2.4,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Oathsworn Blade (50% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.61,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.71,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 0.99,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 2.92,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Oathsworn Blade (100% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 1.71,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.85,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd - 5th Hit",
    "Skill Ratio": 0.66,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "6th Hit (Ares)",
    "Skill Ratio": 3.16,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "Ares Pactstrike",
    Modifier: "1st Hit",
    "Skill Ratio": 0.92,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit (Ares)",
    "Skill Ratio": 0.7,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 0.66,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 0.92,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "5th - 6th Hit (Ares)",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "7th Hit",
    "Skill Ratio": 1.19,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "8th Hit",
    "Skill Ratio": 1.32,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "9th Hit",
    "Skill Ratio": 1.45,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "10th Hit (Ares)",
    "Skill Ratio": 1.1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "11th Hit",
    "Skill Ratio": 2.77,
    "DMG Cap": 24999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "12th Hit (Ares)",
    "Skill Ratio": 2.1,
    "DMG Cap": 24999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "SBA",
    Modifier: "1st Hit",
    "Skill Ratio": 2.1,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 2.5,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 5.6,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "SBA (50% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 2.6,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 3.09,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 6.95,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "SBA (100% Gauge)",
    Modifier: "1st Hit",
    "Skill Ratio": 3.26,
    "DMG Cap": 89999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "",
    Modifier: "2nd - 3rd Hit",
    "Skill Ratio": 0.8,
    "DMG Cap": 89999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "",
    Modifier: "4th Hit (Ares)",
    "Skill Ratio": 1.11,
    "DMG Cap": 89999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "",
    Modifier: "5th Hit",
    "Skill Ratio": 3.96,
    "DMG Cap": 89999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "",
    Modifier: "6th Hit",
    "Skill Ratio": 7.91,
    "DMG Cap": 89999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "Link Attack",
    Modifier: "",
    "Skill Ratio": 6.08,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Li",
  },
  {
    Skill: "Link Attack (50% Gauge)",
    Modifier: "",
    "Skill Ratio": 7.45,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Li",
  },
  {
    Skill: "Link Attack (100% Gauge)",
    Modifier: "Katalina's Hit",
    "Skill Ratio": 7.9,
    "DMG Cap": 99999,
    CD: "",
    Classification: "LiSp",
  },
  {
    Skill: "",
    Modifier: "Ares Hit (Frozen Blade Before)",
    "Skill Ratio": 2,
    "DMG Cap": 9999,
    CD: "",
    Classification: "LiSp",
  },
  {
    Skill: "",
    Modifier: "Ares Hit (Finisher, Pactstrike, Winter's Rain Before)",
    "Skill Ratio": 2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "LiSp",
  },
  {
    Skill: "",
    Modifier: "Ares Hit (Azure Sword Before)",
    "Skill Ratio": 2,
    "DMG Cap": 19999,
    CD: "",
    Classification: "LiSp",
  },
  {
    Skill: "",
    Modifier: "Ares Hit (Last hit of Pactstrike Before)",
    "Skill Ratio": 2,
    "DMG Cap": 24999,
    CD: "",
    Classification: "LiSp",
  },
  {
    Skill: "",
    Modifier: "Ares Hit (Enchanted Lands Before)",
    "Skill Ratio": 2,
    "DMG Cap": 59999,
    CD: "",
    Classification: "LiSp",
  },
  {
    Skill: "Azure Sword",
    Modifier: "1st Hit (Melee)",
    "Skill Ratio": 0.66,
    "DMG Cap": 19999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 3.3,
    "DMG Cap": 19999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit (Ares)",
    "Skill Ratio": 1.5,
    "DMG Cap": 19999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Frozen Blade",
    Modifier: "",
    "Skill Ratio": 2.75,
    "DMG Cap": 9999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Frozen Blade (50% Gauge)",
    Modifier: "",
    "Skill Ratio": 3.06,
    "DMG Cap": 9999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Frozen Blade (100% Gauge)",
    Modifier: "1st - 4th Hit",
    "Skill Ratio": 0.87,
    "DMG Cap": 9999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "5th Hit (Ares)",
    "Skill Ratio": 1.62,
    "DMG Cap": 9999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Winter's Rain",
    Modifier: "1st - 3rd Hit",
    "Skill Ratio": 1.1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 1.6,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "5th Hit",
    "Skill Ratio": 3.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "6th Hit (Spear)",
    "Skill Ratio": 1.89,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Winter's Rain (50% Gauge)",
    Modifier: "1st - 3rd Hit",
    "Skill Ratio": 1.11,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 1.98,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "5th Hit",
    "Skill Ratio": 3.97,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "6th Hit (Spear)",
    "Skill Ratio": 2.46,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Winter's Rain (100% Gauge)",
    Modifier: "1st - 3rd Hit",
    "Skill Ratio": 1.45,
    "DMG Cap": 14999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4th Hit (Ares)",
    "Skill Ratio": 1.3,
    "DMG Cap": 14999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "5th Hit",
    "Skill Ratio": 2.11,
    "DMG Cap": 14999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "6th Hit (Ares)",
    "Skill Ratio": 1.3,
    "DMG Cap": 14999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "7th Hit",
    "Skill Ratio": 4.22,
    "DMG Cap": 14999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "8th Hit (Ares)",
    "Skill Ratio": 2.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "9th Hit (Spear)",
    "Skill Ratio": 2.64,
    "DMG Cap": 14999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Enchanted Lands",
    Modifier: "",
    "Skill Ratio": 3.62,
    "DMG Cap": 59999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Enchanted Lands (50% Gauge)",
    Modifier: "",
    "Skill Ratio": 4.5,
    "DMG Cap": 59999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Enchanted Lands (100% Gauge)",
    Modifier: "1st - 6th Hit",
    "Skill Ratio": 0.45,
    "DMG Cap": 59999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "7th Hit (Ares)",
    "Skill Ratio": 3.84,
    "DMG Cap": 59999,
    CD: "",
    Classification: "SkSp",
  },
];

export const katalinaSkills = convertSkills(skillsJson);
