import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Dawnfly Auto",
    Modifier: "1st Auto",
    "Skill Ratio": 1.3,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Auto",
    "Skill Ratio": 1.65,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Auto",
    "Skill Ratio": 1.25,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Auto (2nd Hit)",
    "Skill Ratio": 1.8,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Auto",
    "Skill Ratio": 4.8,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Dawnfly Charge",
    Modifier: "Level 1",
    "Skill Ratio": 1.85,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "Level 2",
    "Skill Ratio": 1.85,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "Level 3",
    "Skill Ratio": 4.8,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "Finisher",
    "Skill Ratio": 1.85,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoChFi",
  },
  {
    Skill: "",
    Modifier: "All (x?)",
    "Skill Ratio": 0.7,
    "DMG Cap": 9999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "Freeflutter Auto",
    Modifier: "1st Auto",
    "Skill Ratio": 1,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "2nd Auto",
    "Skill Ratio": 1.2,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "3rd Auto",
    "Skill Ratio": 0.8,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "3rd Auto (2nd Hit)",
    "Skill Ratio": 1.4,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "4th Auto",
    "Skill Ratio": 0.7,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "4th Auto (2nd Hit)",
    "Skill Ratio": 2.2,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "5th Auto",
    "Skill Ratio": 0.7,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "6th Auto",
    "Skill Ratio": 0.7,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "7th Auto",
    "Skill Ratio": 0.7,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "8th Auto",
    "Skill Ratio": 0.75,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "Finisher (x5)",
    "Skill Ratio": 0.8,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "Finisher (Final Hit)",
    "Skill Ratio": 1.45,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Switch Stance",
    Modifier: "-> Freeflutter",
    "Skill Ratio": 1,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "-> Dawnfly",
    "Skill Ratio": 1,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "Switch Stance (Buffed)",
    Modifier: "-> Freeflutter",
    "Skill Ratio": 2.6,
    "DMG Cap": 7999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "-> Freeflutter (Projectile)",
    "Skill Ratio": 2.6,
    "DMG Cap": 7999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "-> Freeflutter (x13)",
    "Skill Ratio": 0.3,
    "DMG Cap": 7999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "-> Dawnfly",
    "Skill Ratio": 3.4,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "",
    Modifier: "-> Dawnfly (x5)",
    "Skill Ratio": 0.5,
    "DMG Cap": 7999,
    CD: "",
    Classification: "NoSp",
  },
  {
    Skill: "Setsuna",
    Modifier: "Level 1",
    "Skill Ratio": 4.1,
    "DMG Cap": 199999,
    CD: "",
    Classification: "SkChSp",
  },
  {
    Skill: "",
    Modifier: "Level 1 (2nd Hit)",
    "Skill Ratio": 6.1,
    "DMG Cap": 199999,
    CD: "",
    Classification: "SkChSp",
  },
  {
    Skill: "",
    Modifier: "Level 2",
    "Skill Ratio": 6.25,
    "DMG Cap": 199999,
    CD: "",
    Classification: "SkChSp",
  },
  {
    Skill: "",
    Modifier: "Level 2 (2nd Hit)",
    "Skill Ratio": 9.4,
    "DMG Cap": 199999,
    CD: "",
    Classification: "SkChSp",
  },
  {
    Skill: "",
    Modifier: "Level 3",
    "Skill Ratio": 10.2,
    "DMG Cap": 199999,
    CD: "",
    Classification: "SkChSp",
  },
  {
    Skill: "",
    Modifier: "Level 3 (2nd Hit)",
    "Skill Ratio": 15.3,
    "DMG Cap": 199999,
    CD: "",
    Classification: "SkChSp",
  },
  {
    Skill: "Kyokasuigetsu",
    Modifier: "0 Butterfly",
    "Skill Ratio": 2.6,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "1 Butterfly",
    "Skill Ratio": 2.6,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "1 Butterfly (x1)",
    "Skill Ratio": 0.7,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2 Butterfly",
    "Skill Ratio": 4,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2 Butterfly (x2)",
    "Skill Ratio": 0.7,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3 Butterfly",
    "Skill Ratio": 4,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3 Butterfly (x3)",
    "Skill Ratio": 0.8,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4 Butterfly",
    "Skill Ratio": 5.2,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4 Butterfly (x4)",
    "Skill Ratio": 0.8,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "5 Butterfly",
    "Skill Ratio": 5.2,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "5 Butterfly (x5)",
    "Skill Ratio": 0.9,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "6 Butterfly",
    "Skill Ratio": 6.5,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "6 Butterfly (x6)",
    "Skill Ratio": 0.9,
    "DMG Cap": 34999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Transient (Freeflutter)",
    Modifier: "1st Hit",
    "Skill Ratio": 2.35,
    "DMG Cap": 44999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 2.9,
    "DMG Cap": 44999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 1,
    "DMG Cap": 44999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 3.4,
    "DMG Cap": 44999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "Extra (x?)",
    "Skill Ratio": 3,
    "DMG Cap": 44999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Transient (Dawnfly)",
    Modifier: "0 Butterfly (x7)",
    "Skill Ratio": 0.3,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "0 Butterfly (Last)",
    "Skill Ratio": 3,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "1 Butterfly (x7)",
    "Skill Ratio": 0.5,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "1 Butterfly (Last)",
    "Skill Ratio": 3,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "2 Butterfly (x7)",
    "Skill Ratio": 0.55,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "2 Butterfly (Last)",
    "Skill Ratio": 4.4,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "3 Butterfly (x8)",
    "Skill Ratio": 0.55,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "3 Butterfly (Last)",
    "Skill Ratio": 5,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "4 Butterfly (x9)",
    "Skill Ratio": 0.8,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "4 Butterfly (Last)",
    "Skill Ratio": 5,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "5 Butterfly (x10)",
    "Skill Ratio": 0.8,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "5 Butterfly (Last)",
    "Skill Ratio": 5,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "6 Butterfly (x11)",
    "Skill Ratio": 0.8,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "6 Butterfly (Last)",
    "Skill Ratio": 5,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Link",
    Modifier: "",
    "Skill Ratio": 6,
    "DMG Cap": 99999,
    CD: "",
    Classification: "LiSp",
  },
  {
    Skill: "SBA",
    Modifier: "Activation",
    "Skill Ratio": 0.5,
    "DMG Cap": 99999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "",
    Modifier: "1st Hit",
    "Skill Ratio": 1.5,
    "DMG Cap": 64999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 1.5,
    "DMG Cap": 64999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 0.8,
    "DMG Cap": 64999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "",
    Modifier: "4th HIt",
    "Skill Ratio": 6.1,
    "DMG Cap": 64999,
    CD: "",
    Classification: "SbSp",
  },
  {
    Skill: "Crescent Moon",
    Modifier: "0 Butterfly",
    "Skill Ratio": 0.8,
    "DMG Cap": 39999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "1 Butterfly",
    "Skill Ratio": 1,
    "DMG Cap": 39999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2 Butterfly (x2)",
    "Skill Ratio": 1,
    "DMG Cap": 39999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3 Butterfly (x3)",
    "Skill Ratio": 1,
    "DMG Cap": 39999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4 Butterfly (x3)",
    "Skill Ratio": 1.4,
    "DMG Cap": 39999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "5 Butterfly (x3)",
    "Skill Ratio": 1.9,
    "DMG Cap": 39999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "6 Butterfly (x3)",
    "Skill Ratio": 2.5,
    "DMG Cap": 39999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "Apex of Nothingness",
    Modifier: "0 Butterfly (No Counter)",
    "Skill Ratio": 1.5,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "0 Butterfly (Hit 1)",
    "Skill Ratio": 0.6,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "0 Butterfly (Hit 2)",
    "Skill Ratio": 3.25,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "1 Butterfly (No Counter)",
    "Skill Ratio": 1.8,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "1 Butterfly (Hit 1)",
    "Skill Ratio": 0.85,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "1 Butterfly (Hit 2)",
    "Skill Ratio": 4,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2 Butterfly (No Counter)",
    "Skill Ratio": 2.1,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2 Butterfly (Hit 1)",
    "Skill Ratio": 1.1,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "2 Butterfly (Hit 2)",
    "Skill Ratio": 4.7,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3 Butterfly (No Counter)",
    "Skill Ratio": 2.4,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3 Butterfly (Hit 1)",
    "Skill Ratio": 1.3,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "3 Butterfly (Hit 2)",
    "Skill Ratio": 5.4,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4 Butterfly (No Counter)",
    "Skill Ratio": 2.7,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4 Butterfly (Hit 1)",
    "Skill Ratio": 1.6,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "4 Butterfly (Hit 2)",
    "Skill Ratio": 6.15,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "5 Butterfly (No Counter)",
    "Skill Ratio": 3,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "5 Butterfly (Hit 1)",
    "Skill Ratio": 1.8,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "5 Butterfly (Hit 2)",
    "Skill Ratio": 6.8,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "6 Butterfly (No Counter)",
    "Skill Ratio": 3.3,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "6 Butterfly (Hit 1)",
    "Skill Ratio": 2.1,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
  {
    Skill: "",
    Modifier: "6 Butterfly (Hit 2)",
    "Skill Ratio": 7.6,
    "DMG Cap": 84999,
    CD: "",
    Classification: "SkSp",
  },
];

export const narmayaSkills = convertSkills(skillsJson);
