import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Basic Attack",
    Modifier: "1st Attack",
    "Skill Ratio": 1.31,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Attack",
    "Skill Ratio": 2.2,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Attack",
    "Skill Ratio": 1.74,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Attack",
    "Skill Ratio": 3,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Combo Finisher",
    "Skill Ratio": 5.19,
    "DMG Cap": 19999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Launch",
    Modifier: "",
    "Skill Ratio": 1,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Aerial Attack",
    Modifier: "1st Attack",
    "Skill Ratio": 1.09,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd Attack",
    "Skill Ratio": 1.45,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd Attack",
    "Skill Ratio": 0.84,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th Attack",
    "Skill Ratio": 1.45,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Schlacht",
    Modifier: "",
    "Skill Ratio": 5,
    "DMG Cap": 24999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "Schlacht+",
    Modifier: "1st Swing",
    "Skill Ratio": 2.5,
    "DMG Cap": 24999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "Schlacht+",
    Modifier: "2nd Swing",
    "Skill Ratio": 5.61,
    "DMG Cap": 24999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "Schlacht++",
    Modifier: "Upward Swing",
    "Skill Ratio": 5,
    "DMG Cap": 79999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "Schlacht++",
    Modifier: "Downward Swing",
    "Skill Ratio": 8.4,
    "DMG Cap": 79999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "Aerial Barrage (Schlacht)",
    Modifier: "",
    "Skill Ratio": 1.6,
    "DMG Cap": 19999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Link Attack",
    Modifier: "",
    "Skill Ratio": 6.01,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Li",
  },
  {
    Skill: "SBA",
    Modifier: "Activation Hit",
    "Skill Ratio": 1,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "1st Hit",
    "Skill Ratio": 1.48,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "2nd-10th Hit",
    "Skill Ratio": 0.4,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "11th Hit",
    "Skill Ratio": 6,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "Roter Wirbel",
    Modifier: "1st Hit",
    "Skill Ratio": 6.04,
    "DMG Cap": 9999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "2nd-17th Hit",
    "Skill Ratio": 1.98,
    "DMG Cap": 9999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Roter Wirbel (Schlacht)",
    Modifier: "bug",
    "Skill Ratio": 1.98,
    "DMG Cap": 79999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Feuerangriff",
    Modifier: "1st Hit",
    "Skill Ratio": 2.98,
    "DMG Cap": 84999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 4.65,
    "DMG Cap": 84999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "3rd Hit",
    "Skill Ratio": 6.66,
    "DMG Cap": 84999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "4th Hit",
    "Skill Ratio": 8.83,
    "DMG Cap": 84999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Macht",
    Modifier: "1st-4th Hit",
    "Skill Ratio": 0.8,
    "DMG Cap": 19999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "5th Hit",
    "Skill Ratio": 5.8,
    "DMG Cap": 19999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Royal Authority",
    Modifier: "1st Hit",
    "Skill Ratio": 4.31,
    "DMG Cap": 54999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "2nd Hit",
    "Skill Ratio": 8.56,
    "DMG Cap": 54999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Zerreissen",
    Modifier: "",
    "Skill Ratio": 3.9,
    "DMG Cap": 24999,
    CD: "",
    Classification: "Sk",
  },
];

export const percivalSkills = convertSkills(skillsJson);
