import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Auto Attack",
    Modifier: "",
    "Skill Ratio": 0.17,
    "DMG Cap": 1999,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "Burst Fire",
    Modifier: "Norrmal",
    "Skill Ratio": 0.34,
    "DMG Cap": 4999,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "",
    Modifier: "3 shot",
    "Skill Ratio": 1.02,
    "DMG Cap": 14997,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "",
    Modifier: "4 shot",
    "Skill Ratio": 1.36,
    "DMG Cap": 19996,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "Bull's Eye Blast",
    Modifier: "Uncharged",
    "Skill Ratio": 0.16,
    "DMG Cap": 1999,
    CD: "",
    Classification: "NoRaCh",
  },
  {
    Skill: "Bull's Eye Blast",
    Modifier: "Uncharged total",
    "Skill Ratio": 1.6,
    "DMG Cap": 19990,
    CD: "",
    Classification: "NoRaCh",
  },
  {
    Skill: "Bull's Eye Blast",
    Modifier: "First hit",
    "Skill Ratio": 4.93,
    "DMG Cap": 39999,
    CD: "",
    Classification: "NoRaCh",
  },
  {
    Skill: "Bull's Eye Blast",
    Modifier: "Second hit",
    "Skill Ratio": 2.79,
    "DMG Cap": 39999,
    CD: "",
    Classification: "NoRaCh",
  },
  {
    Skill: "Bull's Eye Blast",
    Modifier: "Total",
    "Skill Ratio": 7.67,
    "DMG Cap": 79998,
    CD: "",
    Classification: "NoRaCh",
  },
  {
    Skill: "Link Attack (Total)",
    Modifier: "",
    "Skill Ratio": 6.59,
    "DMG Cap": 99999,
    CD: "",
    Classification: "LiRa",
  },
  {
    Skill: "SBA",
    Modifier: "",
    "Skill Ratio": 15.83,
    "DMG Cap": 375228,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "Launch",
    Modifier: "",
    "Skill Ratio": 0.52,
    "DMG Cap": 1999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Aerial Combo",
    Modifier: "I",
    "Skill Ratio": 0.17,
    "DMG Cap": 1999,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "Aerial Combo Total",
    Modifier: "",
    "Skill Ratio": 0.85,
    "DMG Cap": 9995,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "Aerial Barrage (Aerial Shotgun)",
    Modifier: "II",
    "Skill Ratio": 0.5,
    "DMG Cap": 39999,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "Aerial Barrage Total",
    Modifier: "",
    "Skill Ratio": 4,
    "DMG Cap": 319992,
    CD: "",
    Classification: "NoRa",
  },
  {
    Skill: "Spitfire",
    Modifier: "First hit",
    "Skill Ratio": 4.4,
    "DMG Cap": 44999,
    CD: 23,
    Classification: "SkRa",
  },
  {
    Skill: "",
    Modifier: "Second hit",
    "Skill Ratio": 2.2,
    "DMG Cap": 44999,
    CD: 23,
    Classification: "SkRa",
  },
  {
    Skill: "Coffinmaker",
    Modifier: "",
    "Skill Ratio": 0.6,
    "DMG Cap": 5999,
    CD: 60,
    Classification: "SkRa",
  },
  {
    Skill: "",
    Modifier: "Final bullet",
    "Skill Ratio": 1.35,
    "DMG Cap": 5999,
    CD: "",
    Classification: "SkRa",
  },
  {
    Skill: "",
    Modifier: "Total",
    "Skill Ratio": 27.75,
    "DMG Cap": 269955,
    CD: "",
    Classification: "SkRa",
  },
  {
    Skill: "Bullet Hail",
    Modifier: "Per hit",
    "Skill Ratio": 1,
    "DMG Cap": 6999,
    CD: 45,
    Classification: "SkRa",
  },
  {
    Skill: "",
    Modifier: "Total",
    "Skill Ratio": 14.81,
    "DMG Cap": 104985,
    CD: "",
    Classification: "SkRa",
  },
  {
    Skill: "Slag Shot",
    Modifier: "Per hit",
    "Skill Ratio": 0.68,
    "DMG Cap": 4999,
    CD: 48,
    Classification: "SkRa",
  },
  {
    Skill: "",
    Modifier: "Maximum",
    "Skill Ratio": 6.15,
    "DMG Cap": 179964,
    CD: "",
    Classification: "SkRa",
  },
  {
    Skill: "Collateral Damage Hit 1",
    Modifier: "First hit",
    "Skill Ratio": 43,
    "DMG Cap": 249999,
    CD: 123,
    Classification: "SkRa",
  },
  {
    Skill: "",
    Modifier: "Second hit",
    "Skill Ratio": 3.3,
    "DMG Cap": 249999,
    CD: "",
    Classification: "SkRa",
  },
  {
    Skill: "Wild Gunsmoke",
    Modifier: "",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    CD: 75,
    Classification: "",
  },
  {
    Skill: "Double Tap",
    Modifier: "",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    CD: 83,
    Classification: "",
  },
  {
    Skill: "Duration",
    Modifier: "",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    CD: 25,
    Classification: "",
  },
];

export const rackamSkills = convertSkills(skillsJson);
