import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Basic Attack",
    Modifier: "First Attack",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Second Attack",
    "Skill Ratio": 1.1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Third Attack",
    "Skill Ratio": 1.5,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Fourth Attack",
    "Skill Ratio": 1.7,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Finisher A",
    Modifier: "First Attack",
    "Skill Ratio": 1.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Finisher B",
    Modifier: "First Attack",
    "Skill Ratio": 0.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "Second Attack",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Finisher C",
    Modifier: "First Attack",
    "Skill Ratio": 0.6,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "Second Attack",
    "Skill Ratio": 0.6,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "Third Attack",
    "Skill Ratio": 1.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Finisher D",
    Modifier: "First Attack",
    "Skill Ratio": 0.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "Second Attack",
    "Skill Ratio": 0.6,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "Third Attack",
    "Skill Ratio": 0.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "Fourth Attack",
    "Skill Ratio": 1.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Rose Attacks",
    Modifier: "Regular",
    "Skill Ratio": 0.3,
    "DMG Cap": 4999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Launch",
    Modifier: "Regular",
    "Skill Ratio": 1.2,
    "DMG Cap": 4999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Air Combo",
    Modifier: "First Attack",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Second Attack",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Third Attack",
    "Skill Ratio": 1.5,
    "DMG Cap": 9999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Aerial Barrage",
    Modifier: "First Attack",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "",
    Modifier: "Second Attack",
    "Skill Ratio": 1,
    "DMG Cap": 9999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Link Attack",
    Modifier: "First Attack",
    "Skill Ratio": 6,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Li",
  },
  {
    Skill: "SBA",
    Modifier: "Activation",
    "Skill Ratio": 1,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "First Attack",
    "Skill Ratio": 0.6,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Second Attack",
    "Skill Ratio": 0.7,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Third Attack",
    "Skill Ratio": 0.8,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Fourth Attack",
    "Skill Ratio": 1.1,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Fifth Attack",
    "Skill Ratio": 1.4,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Sixth Attack",
    "Skill Ratio": 1.8,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Seventh Attack",
    "Skill Ratio": 3.5,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Total",
    "Skill Ratio": 10.9,
    "DMG Cap": 319992,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "Rose Tycoon",
    Modifier: "Level 1",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: "35s",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 2",
    "Skill Ratio": 1.1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 3",
    "Skill Ratio": 1.4,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 4",
    "Skill Ratio": 1.6,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Lost Love",
    Modifier: "Level 1",
    "Skill Ratio": 4.4,
    "DMG Cap": 99999,
    CD: "105s",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 2",
    "Skill Ratio": 6.16,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 3",
    "Skill Ratio": 8.8,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 4",
    "Skill Ratio": 13.2,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Spiral Rose",
    Modifier: "Penultimate Hits",
    "Skill Ratio": 0.6,
    "DMG Cap": 4999,
    CD: "40s",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Final Hit",
    "Skill Ratio": 1,
    "DMG Cap": 4999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 1 Rose Hit",
    "Skill Ratio": 0.45,
    "DMG Cap": 4999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 2 Rose Hit",
    "Skill Ratio": 0.6,
    "DMG Cap": 4999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 3 Rose Hit",
    "Skill Ratio": 0.75,
    "DMG Cap": 4999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Level 4 Rose Hit",
    "Skill Ratio": 0.9,
    "DMG Cap": 4999,
    CD: "",
    Classification: "Sk",
  },
];

export const rosettaSkills = convertSkills(skillsJson);
