import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Basic Attack",
    Modifier: "First Hit",
    "Skill Ratio": 0.3459,
    "DMG Cap": 3499,
    Classification: "NoRa",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Second Hit",
    "Skill Ratio": 0.3459,
    "DMG Cap": 3499,
    Classification: "NoRa",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Third Hit",
    "Skill Ratio": 0.3459,
    "DMG Cap": 3499,
    Classification: "NoRa",
    CD: 0,
  },
  {
    Skill: "Charged Attack",
    Modifier: "First Hit",
    "Skill Ratio": 1.0161,
    "DMG Cap": 9999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Second Hit",
    "Skill Ratio": 1.0161,
    "DMG Cap": 9999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Third Hit",
    "Skill Ratio": 1.0161,
    "DMG Cap": 9999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "Combo Finisher",
    Modifier: "XY",
    "Skill Ratio": 0.8993,
    "DMG Cap": 12999,
    Classification: "NoRaFi",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "XXY",
    "Skill Ratio": 0.1989,
    "DMG Cap": 3499,
    Classification: "NoRaFi",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "XXXY",
    "Skill Ratio": 1.1934,
    "DMG Cap": 15999,
    Classification: "NoRaFi",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "XY Charged",
    "Skill Ratio": 1.326,
    "DMG Cap": 19999,
    Classification: "NoRaFiCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "XXY Charged",
    "Skill Ratio": 0.49,
    "DMG Cap": 3499,
    Classification: "NoRaFiCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "XXXY Charged",
    "Skill Ratio": 2.7096,
    "DMG Cap": 34999,
    Classification: "NoRaFiCh",
    CD: 0,
  },
  {
    Skill: "Power Finisher",
    Modifier: "XYY",
    "Skill Ratio": 1.5911,
    "DMG Cap": 12999,
    Classification: "NoRaFi",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "XXYY",
    "Skill Ratio": 0.1902,
    "DMG Cap": 3499,
    Classification: "NoRaFi",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "XXXYY",
    "Skill Ratio": 3.2515,
    "DMG Cap": 15999,
    Classification: "NoRaFi",
    CD: 0,
  },
  {
    Skill: "Power Finisher",
    Modifier: "XYCharged Y",
    "Skill Ratio": 2.0408,
    "DMG Cap": 19999,
    Classification: "NoRaFi",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "XXYCharged Y",
    "Skill Ratio": 0.3459,
    "DMG Cap": 3499,
    Classification: "NoRaFi",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "XXXYCharged Y",
    "Skill Ratio": 3.8049,
    "DMG Cap": 34999,
    Classification: "NoRaFi",
    CD: 0,
  },
  {
    Skill: "Multilock Hail",
    Modifier: "I",
    "Skill Ratio": 0.908,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "II",
    "Skill Ratio": 0.908,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "III",
    "Skill Ratio": 0.908,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "IV",
    "Skill Ratio": 1.0809,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "V",
    "Skill Ratio": 1.0809,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "VI",
    "Skill Ratio": 1.0809,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "VII",
    "Skill Ratio": 1.3548,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "VIII",
    "Skill Ratio": 1.3548,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "IX",
    "Skill Ratio": 1.3548,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "X",
    "Skill Ratio": 1.3548,
    "DMG Cap": 12999,
    Classification: "NoRaCh",
    CD: 0,
  },
  {
    Skill: "Depravity",
    Modifier: "Per hit",
    "Skill Ratio": 0.5322,
    "DMG Cap": 3999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Clincher",
    Modifier: "0 Debuffs",
    "Skill Ratio": 18.1598,
    "DMG Cap": 199999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Clincher",
    Modifier: "1 Debuffs",
    "Skill Ratio": 20.7541,
    "DMG Cap": 199999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Clincher",
    Modifier: "2 Debuffs",
    "Skill Ratio": 25.0113,
    "DMG Cap": 199999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Clincher",
    Modifier: "3 Debuffs",
    "Skill Ratio": 25.9426,
    "DMG Cap": 199999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Clincher",
    Modifier: "4 Debuffs",
    "Skill Ratio": 26.8739,
    "DMG Cap": 199999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Lethal Rain",
    Modifier: "Per hit",
    "Skill Ratio": 2.5943,
    "DMG Cap": 19999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Wheel of Death",
    Modifier: "Per hit",
    "Skill Ratio": 1.0377,
    "DMG Cap": 7999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Valiant Weave",
    Modifier: "Initial Hit",
    "Skill Ratio": 2.3348,
    "DMG Cap": 19999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Two Crown's Strife",
    Modifier: "Initial Hit",
    "Skill Ratio": 53.4417,
    "DMG Cap": 599999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Follow-up",
    "Skill Ratio": 4.7388,
    "DMG Cap": 49999,
    Classification: "RaSk",
    CD: 0,
  },
  {
    Skill: "Bring the Thunder",
    Modifier: "",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    Classification: "",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Depravity",
    "Skill Ratio": 0,
    "DMG Cap": 1999,
    Classification: "Fl",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Wheel of Death",
    "Skill Ratio": 0,
    "DMG Cap": 3999,
    Classification: "Fl",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Lethal Rain",
    "Skill Ratio": 0,
    "DMG Cap": 9999,
    Classification: "Fl",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Valiant Weave",
    "Skill Ratio": 0,
    "DMG Cap": 99999,
    Classification: "Fl",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Clincher",
    "Skill Ratio": 0,
    "DMG Cap": 99999,
    Classification: "Fl",
    CD: 0,
  },
  {
    Skill: "",
    Modifier: "Two Crown's Strife",
    "Skill Ratio": 0,
    "DMG Cap": 299999,
    Classification: "Fl",
    CD: 0,
  },
  {
    Skill: "Merculight",
    Modifier: "",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    Classification: "",
    CD: 0,
  },
  {
    Skill: "Peerless Eye",
    Modifier: "",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    Classification: "",
    CD: 0,
  },
];

export const tweyenSkills = convertSkills(skillsJson);
