import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsJson: SkillJsonRaw[] = [
  {
    Skill: "Basic Attack",
    Modifier: "First Attack",
    "Skill Ratio": 1.3,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Second Attack",
    "Skill Ratio": 2.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Third Attack",
    "Skill Ratio": 3.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Combo A",
    Modifier: "Regular (First Hit)",
    "Skill Ratio": 1,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Regular (Second Hit)",
    "Skill Ratio": 4,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Full Charge (First Hit)",
    "Skill Ratio": 3.2,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "Full Charge (Second Hit)",
    "Skill Ratio": 12.6,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoChFi",
  },
  {
    Skill: "Combo B",
    Modifier: "Regular (First Hit)",
    "Skill Ratio": 1.5,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Regular (Second Hit)",
    "Skill Ratio": 3,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Regular (Third Hit)",
    "Skill Ratio": 3,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Regular (Fourth Hit)",
    "Skill Ratio": 6,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Full Charge (First Hit)",
    "Skill Ratio": 4.7,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "Full Charge (Second Hit)",
    "Skill Ratio": 9.5,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "Full Charge (Third Hit)",
    "Skill Ratio": 9.4,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoChFi",
  },
  {
    Skill: "",
    Modifier: "Full Charge (Fourth Hit)",
    "Skill Ratio": 18.9,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoChFi",
  },
  {
    Skill: "Combo C",
    Modifier: "Regular (First Hit)",
    "Skill Ratio": 5.5,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Regular (Second Hit)",
    "Skill Ratio": 9.5,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Full Charge (First Hit)",
    "Skill Ratio": 24.8,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoCh",
  },
  {
    Skill: "",
    Modifier: "Full Charge (Second Hit)",
    "Skill Ratio": 42.85,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoChFi",
  },
  {
    Skill: "Melas Unleashed",
    Modifier: "Regular",
    "Skill Ratio": 0.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Launch",
    Modifier: "Regular",
    "Skill Ratio": 1,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Air Combo",
    Modifier: "First Attack",
    "Skill Ratio": 1.2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Second Attack",
    "Skill Ratio": 1.8,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Third Attack",
    "Skill Ratio": 2.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Aerial Barrage",
    Modifier: "Regular",
    "Skill Ratio": 1.7,
    "DMG Cap": 14999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Link Attack",
    Modifier: "Regular",
    "Skill Ratio": 5,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Li",
  },
  {
    Skill: "",
    Modifier: "Regular",
    "Skill Ratio": 9.5,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Full Charge",
    "Skill Ratio": 42.85,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoChFi",
  },
  {
    Skill: "SBA",
    Modifier: "First Hit",
    "Skill Ratio": 0.94,
    "DMG Cap": 91578,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Second Hit",
    "Skill Ratio": 1.89,
    "DMG Cap": 4578,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Multi Hits",
    "Skill Ratio": 0.19,
    "DMG Cap": 4578,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "Final Hit",
    "Skill Ratio": 1.89,
    "DMG Cap": 4578,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "Battalions of Fear",
    Modifier: "Regular",
    "Skill Ratio": 5.42,
    "DMG Cap": 64999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Regular",
    "Skill Ratio": 9.5,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Full Charge",
    "Skill Ratio": 42.85,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoChFi",
  },
  {
    Skill: "Great Scythe Grynoth",
    Modifier: "Regular",
    "Skill Ratio": 7.5,
    "DMG Cap": 89999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Regular",
    "Skill Ratio": 9.5,
    "DMG Cap": 39999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "Full Charge",
    "Skill Ratio": 42.85,
    "DMG Cap": 249999,
    CD: "",
    Classification: "NoChFi",
  },
  {
    Skill: "Damnation",
    Modifier: "Regular",
    "Skill Ratio": 12.04,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Umbral Eclipse",
    Modifier: "Regular",
    "Skill Ratio": 2.5,
    "DMG Cap": 29999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Violent Shadows",
    Modifier: "Multi Hits",
    "Skill Ratio": 2.5,
    "DMG Cap": 49999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Penultimate Hit",
    "Skill Ratio": 2.13,
    "DMG Cap": 49999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Final Hit",
    "Skill Ratio": 6.96,
    "DMG Cap": 49999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Netherwrath",
    Modifier: "Regular (Uncharged)",
    "Skill Ratio": 4.17,
    "DMG Cap": 299999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "Counter",
    "Skill Ratio": 10,
    "DMG Cap": 299999,
    CD: "",
    Classification: "Sk",
  },
];

export const vaseragaSkills = convertSkills(skillsJson);
