import { SkillJsonRaw } from "@/types/skill.types";
import { convertSkills } from "./skillConverter";

const skillsConverted: SkillJsonRaw[] = [
  {
    Skill: "Normal Attack",
    Modifier: "1st auto",
    "Skill Ratio": 1,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd",
    "Skill Ratio": 1.5,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd",
    "Skill Ratio": 2,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th (jump)",
    "Skill Ratio": 1.5,
    "DMG Cap": 22999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Loop",
    Modifier: "1st hit",
    "Skill Ratio": 2.5,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "1st jump",
    "Skill Ratio": 1,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd hit",
    "Skill Ratio": 3,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd jump",
    "Skill Ratio": 1.13,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd hit",
    "Skill Ratio": 3.5,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd jump",
    "Skill Ratio": 1.28,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th hit",
    "Skill Ratio": 4,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4+ jump",
    "Skill Ratio": 1.43,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "5+ hit",
    "Skill Ratio": 4.5,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Loop Finisher",
    Modifier: "0 loops big",
    "Skill Ratio": 7.82,
    "DMG Cap": 59999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "0 small",
    "Skill Ratio": 1.1,
    "DMG Cap": 59999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "1 loop big",
    "Skill Ratio": 9.22,
    "DMG Cap": 59999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "1 small",
    "Skill Ratio": 1.32,
    "DMG Cap": 59999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "2 loops big",
    "Skill Ratio": 10.84,
    "DMG Cap": 59999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "2 small",
    "Skill Ratio": 1.54,
    "DMG Cap": 59999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Arvess Hammer",
    Modifier: "3 loops big",
    "Skill Ratio": 18.7,
    "DMG Cap": 99999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "3 small",
    "Skill Ratio": 1.76,
    "DMG Cap": 99999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "4+ loops big",
    "Skill Ratio": 20.6,
    "DMG Cap": 99999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "",
    Modifier: "4+ small",
    "Skill Ratio": 1.98,
    "DMG Cap": 99999,
    CD: "",
    Classification: "NoFiSp",
  },
  {
    Skill: "Y Parry",
    Modifier: "Rhapsody",
    "Skill Ratio": 2.2,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Launch",
    Modifier: "",
    "Skill Ratio": 1,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Air Combo",
    Modifier: "1st hit",
    "Skill Ratio": 1.1,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "2nd",
    "Skill Ratio": 1.3,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "3rd",
    "Skill Ratio": 1.5,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "",
    Modifier: "4th (jump)",
    "Skill Ratio": 0.5,
    "DMG Cap": 22999,
    CD: "",
    Classification: "NoFi",
  },
  {
    Skill: "Air Y",
    Modifier: "Aerial Barrage",
    "Skill Ratio": 1.7,
    "DMG Cap": 22999,
    CD: "",
    Classification: "No",
  },
  {
    Skill: "Link Attack",
    Modifier: "",
    "Skill Ratio": 6.1,
    "DMG Cap": 99999,
    CD: "",
    Classification: "NoLi",
  },
  {
    Skill: "SBA",
    Modifier: "initial hit (never crit)",
    "Skill Ratio": 0.5,
    "DMG Cap": 99999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "1st hit",
    "Skill Ratio": 3.04,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "2nd hit",
    "Skill Ratio": 10.08,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "3rd-10th hits",
    "Skill Ratio": 0.21,
    "DMG Cap": 39999,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "",
    Modifier: "total",
    "Skill Ratio": 14.79,
    "DMG Cap": 479984,
    CD: "",
    Classification: "Sb",
  },
  {
    Skill: "Spear of Arvess",
    Modifier: "",
    "Skill Ratio": 4.94,
    "DMG Cap": 44999,
    CD: 15,
    Classification: "Sk",
  },
  {
    Skill: "Infinite Wonders",
    Modifier: "per hit",
    "Skill Ratio": 0.83,
    "DMG Cap": 6999,
    CD: 18,
    Classification: "RaSk",
  },
  {
    Skill: "",
    Modifier: "total",
    "Skill Ratio": 4.17,
    "DMG Cap": 34994,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "Rain of Fury",
    Modifier: "per hit",
    "Skill Ratio": 1.5,
    "DMG Cap": 14999,
    CD: 48,
    Classification: "RaSk",
  },
  {
    Skill: "",
    Modifier: "total",
    "Skill Ratio": 9,
    "DMG Cap": 89992,
    CD: "",
    Classification: "RaSk",
  },
  {
    Skill: "Wingclipper",
    Modifier: "1st hit",
    "Skill Ratio": 4.04,
    "DMG Cap": 49999,
    CD: 133,
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "2nd",
    "Skill Ratio": 7.96,
    "DMG Cap": 49999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "3rd",
    "Skill Ratio": 10,
    "DMG Cap": 49999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Thousand Flames",
    Modifier: "",
    "Skill Ratio": 3.54,
    "DMG Cap": 29999,
    CD: 70,
    Classification: "RaSk",
  },
  {
    Skill: "",
    Modifier: "burn",
    "Skill Ratio": 2,
    "DMG Cap": 0,
    CD: "",
    Classification: "",
  },
  {
    Skill: "Realm's Majesty",
    Modifier: "1st",
    "Skill Ratio": 1.67,
    "DMG Cap": 54999,
    CD: 30,
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "2nd",
    "Skill Ratio": 5,
    "DMG Cap": 54999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "3rd (jump)",
    "Skill Ratio": 2,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "",
    Modifier: "no parry",
    "Skill Ratio": 3.5,
    "DMG Cap": 14999,
    CD: "",
    Classification: "Sk",
  },
  {
    Skill: "Vengeful Flames",
    Modifier: "",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    CD: 83,
    Classification: "",
  },
  {
    Skill: "Signo Drive",
    Modifier: "",
    "Skill Ratio": 0,
    "DMG Cap": 0,
    CD: 60,
    Classification: "",
  },
];

export const zetaSkills = convertSkills(skillsConverted);
